CREATE TABLE IF NOT EXISTS department (
    department_id SERIAL PRIMARY KEY,
	faculty_id INTEGER NOT NULL REFERENCES faculty (faculty_id) ON DELETE CASCADE ON UPDATE CASCADE,
	department_name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
